Repository DeveloperAcademy-POSTECH/MacC-Team11-UMM, pull requests merged in 2023-10, with the labels that each got.

#7 🧹[#6] fastlane을 설치합니다.
  Gemfile
  Gemfile.lock
  fastlane/Appfile
  fastlane/Fastfile
Labels: :broom: chore

#9 :zap:[#8] 코어데이터 초기 세팅 완료
  UMM.xcodeproj/project.pbxproj
  UMM/ContentView.swift
  UMM/UMM.xcdatamodeld/UMM.xcdatamodel/contents
Labels: :zap: feat

#13 ⚡️[#12]SwiftLint 규칙에 따라 수정
  UMM/Persistence.swift
  UMM/UMMApp.swift
Labels: :zap: feat

#22 🧹[#21] startDate의 데이터 타입을 String?으로 변경합니다.
  UMM/UMM.xcdatamodeld/UMM.xcdatamodel/contents
Labels: :broom: chore

#28 :zap:[#11] 문자열 분류 메서드(1) - 금액, 단위 등 단어의 범주를 분류합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/.DS_Store
  UMM/Enumeration/CharacterForm.swift
  UMM/Enumeration/ExpenseInfoCategory.swift
  UMM/Enumeration/PaymentMethod.swift
  UMM/Enumeration/SplitVariety.swift
  UMM/Extension/Array<CharacterForm>+Extension.swift
  UMM/Extension/Array<String>+Extension.swift
  UMM/Extension/Character+Extension.swift
  UMM/Extension/String+Extension.swift
  UMM/View/ContentView.swift
  UMM/View/RecordView.swift
  UMM/ViewModel/RecordViewModel.swift
Labels: ⚡️ feat

#29 :broom:[#24] UMMApp에서 환경객체 삭제
  UMM/UMMApp.swift
Labels: :broom: chore

#33 ⚡️[#20] STT 기능을 구현합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/View/RecordView.swift
  UMM/ViewModel/RecordViewModel.swift
Labels: ⚡️ feat

#40 🧹[#39] startDate의 데이터 타입을 변경합니다.
  UMM/UMM.xcdatamodeld/UMM.xcdatamodel/contents
Labels: :broom: chore

#37 :zap:[#18] 문자열 분류 메서드 (2) - 구매내역을 카테고리별로 분류합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/Enumeration/ExpenseInfoCategory.swift
  UMM/Model/Enumeration/CharacterForm.swift
  UMM/Model/Enumeration/ExpenseInfoCategory.swift
  UMM/Model/Enumeration/PaymentMethod.swift
  UMM/Model/Enumeration/SplitVariety.swift
  UMM/Model/InfoClassifier.mlmodel
  UMM/Model/Persistence.swift
  UMM/Model/UMM.xcdatamodeld/UMM.xcdatamodel/contents
  UMM/View/RecordView.swift
  UMM/ViewModel/RecordViewModel.swift
Labels: ⚡️ feat

#46 ⚡️[#32] AddTravelView의 캘린더 기본 기능과 UI를 구현합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/UMMApp.swift
  UMM/View/AddMemberView.swift
  UMM/View/AddTravelView.swift
  UMM/ViewModel/AddTravelViewModel.swift
Labels: ⚡️ feat, :art: gui

#48 🧩[#38] Color에셋과 Font에셋을 추가합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/Assets.xcassets/Gray Scale/Contents.json
  UMM/Assets.xcassets/Gray Scale/gray100.colorset/Contents.json
  UMM/Assets.xcassets/Gray Scale/gray200.colorset/Contents.json
  UMM/Assets.xcassets/Gray Scale/gray300.colorset/Contents.json
  UMM/Assets.xcassets/Gray Scale/gray400.colorset/Contents.json
  UMM/Assets.xcassets/Primary/Contents.json
  UMM/Assets.xcassets/Primary/mainOrange.colorset/Contents.json
  UMM/Assets.xcassets/Primary/mainPink.colorset/Contents.json
  UMM/DesignSystem/ButtonTheme.swift
  UMM/DesignSystem/Fonts/FontsManager.swift
  UMM/DesignSystem/Fonts/Pretendard-Black.otf
  UMM/DesignSystem/Fonts/Pretendard-Bold.otf
  UMM/DesignSystem/Fonts/Pretendard-ExtraBold.otf
  UMM/DesignSystem/Fonts/Pretendard-ExtraLight.otf
  UMM/DesignSystem/Fonts/Pretendard-Light.otf
  UMM/DesignSystem/Fonts/Pretendard-Medium.otf
  UMM/DesignSystem/Fonts/Pretendard-Regular.otf
  UMM/DesignSystem/Fonts/Pretendard-SemiBold.otf
  UMM/DesignSystem/Fonts/Pretendard-Thin.otf
  UMM/Extension/Color+Extension.swift
  UMM/Info.plist
Labels: :heart: asset, 🧩 design

#52 :bug:[#51] 깃 충돌 해결 후 origin/dev pull 받음
  .DS_Store
  UMM.xcodeproj/project.pbxproj
  UMM/Dummy/DummyData.swift
  UMM/Extension/Color+Extension.swift
  UMM/Handler/FindCurrentTravelHandler.swift
  UMM/Model/UMM.xcdatamodeld/UMM.xcdatamodel/contents
  UMM/UMMApp.swift
  UMM/View/AllExpenseDetailView.swift
  UMM/View/AllExpenseView.swift
  UMM/View/DummyRecordView.swift
  UMM/View/ExpenseView.swift
  UMM/View/MainView.swift
  UMM/View/TodayExpenseDetailView.swift
  UMM/View/TodayExpenseView.swift
  UMM/ViewModel/DummyRecordViewModel.swift
  UMM/ViewModel/ExpenseViewModel.swift
Labels: :hammer: bug

#61 🎨[#45] RecordView에 연결된 모달 뷰들을 구현합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/Assets.xcassets/Record/Contents.json
  UMM/Assets.xcassets/Record/circleLabelCheck.imageset/Contents.json
  UMM/Assets.xcassets/Record/circleLabelCheck.imageset/Image.png
  UMM/Assets.xcassets/Record/recordAlert.imageset/Contents.json
  UMM/Assets.xcassets/Record/recordAlert.imageset/recordAlert.png
  UMM/Assets.xcassets/Record/recordButtonOn.imageset/Contents.json
  UMM/Assets.xcassets/Record/recordButtonOn.imageset/recordButtonOn.png
  UMM/Dummy/TempSave.swift
  UMM/Extension/Date+Extension.swift
  UMM/Handler/findCurrentTravel.swift
  UMM/Model/Enumeration/Currency.swift
  UMM/View/Record/CompleteRecordView.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/View/Record/RecordView.swift
  UMM/View/Record/TravelChoiceHalfView.swift
  UMM/ViewModel/RecordViewModel.swift
Labels: :art: gui

#59 ⚡️[#47][#58] AddTravelView와 AddMemberView 데이터 선택 기능을 구현합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/DesignSystem/ButtonTheme.swift
  UMM/View/MainView.swift
  UMM/View/Travel/AddMemberView.swift
  UMM/View/Travel/AddTravelView.swift
  UMM/View/Travel/CompleteAddTravelView.swift
  UMM/ViewModel/AddTravelViewModel.swift
Labels: ⚡️ feat, :art: gui

#63 🧩[#57] Typography 적용합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/DesignSystem/Fonts/FontsManager.swift
  UMM/Extension/Font+Extension.swift
  UMM/View/MainView.swift
Labels: 🧩 design

#66 ⚡️[#64] 시작일, 종료일, 정산자 데이터를 Core Data에 저장합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/View/Travel/AddMemberView.swift
  UMM/View/Travel/AddTravelView.swift
  UMM/View/Travel/TravelListView.swift
  UMM/ViewModel/AddMemberViewModel.swift
  UMM/ViewModel/CompleteAddTravelViewModel.swift
Labels: ⚡️ feat

#62 ⚡ [#55] ExpenseView들의 기능 구현
  .DS_Store
  UMM/Dummy/TempSave.swift
  UMM/View/Expense/AllExpenseDetailView.swift
  UMM/View/Expense/AllExpenseView.swift
  UMM/View/Expense/TodayExpenseDetailView.swift
  UMM/View/Expense/TodayExpenseView.swift
  UMM/View/MainView.swift
  UMM/ViewModel/ExpenseViewModel.swift
Labels: ⚡️ feat

#84 ⚡️[#69] TravelListView를 구현합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/View/Other/SettingView.swift
  UMM/View/Travel/AddMemberView.swift
  UMM/View/Travel/CompleteAddTravelView.swift
  UMM/View/Travel/PreviousTravelView.swift
  UMM/View/Travel/TravelListView.swift
  UMM/View/Travel/UpcomingTravelView.swift
  UMM/ViewModel/CompleteAddTravelViewModel.swift
  UMM/ViewModel/PreviousTravelViewModel.swift
  UMM/ViewModel/TravelListViewModel.swift
  UMM/ViewModel/UpcomingTravelViewModel.swift
Labels: ⚡️ feat, :art: gui

#85 :bug:[#70] 녹음 한 번만 되는 에러 해결
  UMM/View/Record/RecordView.swift
  UMM/ViewModel/RecordViewModel.swift
Labels: :hammer: bug

#87 :books:[#86] ReadMe 컨벤션 오타 수정
  README.md
Labels: :books: docs

#89 🎨 [#75] TodayExpenseView의 gui 구현 완료
  UMM.xcodeproj/project.pbxproj
  UMM/Extension/NSObject+Extension.swift
  UMM/UMMApp.swift
  UMM/View/Expense/AllExpenseView.swift
  UMM/View/Expense/CustomDatePicker.swift
  UMM/View/Expense/ExpenseView.swift
  UMM/View/Expense/TodayExpenseView.swift
  UMM/View/MainView.swift
  UMM/ViewModel/ExpenseViewModel.swift
Labels: ⚡️ feat, :art: gui

#90 🎨 [#76] TodayExpenseDetailView gui 완료
  UMM.xcodeproj/project.pbxproj
  UMM/Extension/Font+Extension.swift
  UMM/Handler/dateFormatter.swift
  UMM/Model/Enumeration/Country.swift
  UMM/Model/Enumeration/Currency.swift
  UMM/Model/Enumeration/PaymentMethod.swift
  UMM/View/Expense/AllExpenseDetailView.swift
  UMM/View/Expense/AllExpenseView.swift
  UMM/View/Expense/CustomDatePicker.swift
  UMM/View/Expense/ExpenseView.swift
  UMM/View/Expense/TodayExpenseDetailView.swift
  UMM/View/Expense/TodayExpenseView.swift
  UMM/ViewModel/ExpenseViewModel.swift
Labels: ⚡️ feat, :art: gui

#94 🧩[#90] 추가된 폰트와 색상을 추가합니다.
  UMM/Assets.xcassets/Primary/graphCyan.colorset/Contents.json
  UMM/Assets.xcassets/Primary/graphOrange.colorset/Contents.json
  UMM/Assets.xcassets/Primary/graphPurple.colorset/Contents.json
  UMM/Assets.xcassets/Primary/graphRed.colorset/Contents.json
  UMM/Assets.xcassets/Primary/graphYellow.colorset/Contents.json
  UMM/Extension/Font+Extension.swift
Labels: 🧩 design

#97 🎨 [#77] AllExpenseView, AllExpenseDetailView 구현 완료
  UMM.xcodeproj/project.pbxproj
  UMM/Assets.xcassets/Primary/graphMagenta.colorset/Contents.json
  UMM/Handler/dateFormatter.swift
  UMM/Model/Enumeration/ExpenseInfoCategory.swift
  UMM/View/Expense/AllExpenseDetailView.swift
  UMM/View/Expense/AllExpenseView.swift
  UMM/View/Expense/CustomBarGraph.swift
  UMM/View/Expense/TodayExpenseDetailView.swift
  UMM/View/Expense/TodayExpenseView.swift
  UMM/ViewModel/ExpenseViewModel.swift
  UMM/ViewModel/RecordViewModel.swift
Labels: ⚡️ feat, :art: gui

#98 🎨[#60]AddTravelView, AddMemberView UI 수정합니다.
  UMM/Assets.xcassets/Travel/Contents.json
  UMM/Assets.xcassets/Travel/calendar_left.imageset/Contents.json
  UMM/Assets.xcassets/Travel/calendar_left.imageset/calendar_left.png
  UMM/Assets.xcassets/Travel/calendar_right.imageset/Contents.json
  UMM/Assets.xcassets/Travel/calendar_right.imageset/calendar_right.png
  UMM/Assets.xcassets/Travel/selectActive.imageset/Contents.json
  UMM/Assets.xcassets/Travel/selectActive.imageset/selectActive.png
  UMM/Assets.xcassets/Travel/selectUnactive.imageset/Contents.json
  UMM/Assets.xcassets/Travel/selectUnactive.imageset/selectUnactive.png
  UMM/DesignSystem/ButtonTheme.swift
  UMM/View/Travel/AddMemberView.swift
  UMM/View/Travel/AddTravelView.swift
  UMM/ViewModel/AddTravelViewModel.swift
Labels: :art: gui

#103 ⚡️[#91] TravelListView의 UI를 수정하고 메인 뷰의 탭바를 커스텀합니다.
  UMM/Assets.xcassets/MainTabBar/Contents.json
  UMM/Assets.xcassets/MainTabBar/tabitem1_active.imageset/Contents.json
  UMM/Assets.xcassets/MainTabBar/tabitem1_active.imageset/tabitem1_active.png
  UMM/Assets.xcassets/MainTabBar/tabitem1_unactive.imageset/Contents.json
  UMM/Assets.xcassets/MainTabBar/tabitem1_unactive.imageset/globe3x.png
  UMM/Assets.xcassets/MainTabBar/tabitem2_active.imageset/Contents.json
  UMM/Assets.xcassets/MainTabBar/tabitem2_active.imageset/tabitem2_active.png
  UMM/Assets.xcassets/MainTabBar/tabitem2_unactive.imageset/Contents.json
  UMM/Assets.xcassets/MainTabBar/tabitem2_unactive.imageset/tabitem2_unactive.png
  UMM/Assets.xcassets/MainTabBar/tabitem3_active.imageset/Contents.json
  UMM/Assets.xcassets/MainTabBar/tabitem3_active.imageset/tabitem3_active.png
  UMM/Assets.xcassets/MainTabBar/tabitem3_unactive.imageset/Contents.json
  UMM/Assets.xcassets/MainTabBar/tabitem3_unactive.imageset/tabitem3_unactive.png
  UMM/View/MainView.swift
  UMM/View/Travel/AddMemberView.swift
  UMM/View/Travel/PreviousTravelView.swift
  UMM/View/Travel/TravelListView.swift
  UMM/View/Travel/UpcomingTravelView.swift
  UMM/ViewModel/TravelListViewModel.swift
Labels: ⚡️ feat, :art: gui

#105 🎨[#104] 와이파이 아이콘 수정합니다.
  UMM/Assets.xcassets/Modal/modalCategoryFood.imageset/Contents.json
  UMM/Assets.xcassets/Modal/modalCategoryFun.imageset/Contents.json
  UMM/Assets.xcassets/Modal/modalCategoryPlane.imageset/Contents.json
  UMM/Assets.xcassets/Modal/modalCategoryRoom.imageset/Contents.json
  UMM/Assets.xcassets/Modal/modalCategoryShopping.imageset/Contents.json
  UMM/Assets.xcassets/Modal/modalCategoryTransportation.imageset/Contents.json
  UMM/Assets.xcassets/Modal/modalCategoryUnknown.imageset/Contents.json
  UMM/Assets.xcassets/Record/recordTravelChoiceDownChevron.imageset/Contents.json
  UMM/View/Expense/AllExpenseView.swift
  UMM/View/Expense/ExpenseView.swift
  UMM/View/Expense/TodayExpenseDetailView.swift
  UMM/View/Expense/TodayExpenseView.swift
Labels: :art: gui

#121 ⚡️[#91][#118][#119] 임시기록 뷰를 만들고 TravelListView의 디테일 수정 및 AddMemberView의 오류를 수정합니다.
  UMM/View/Travel/AddMemberView.swift
  UMM/View/Travel/AddTravelView.swift
  UMM/View/Travel/PreviousTravelView.swift
  UMM/View/Travel/TravelListView.swift
  UMM/View/Travel/UpcomingTravelView.swift
  UMM/ViewModel/TravelListViewModel.swift
Labels: ⚡️ feat, :art: gui

#123 ⚡️[#122] TravelDetailView와 관련된 작업들을 진행합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/Assets.xcassets/Travel/dollar-circle.imageset/Contents.json
  UMM/Assets.xcassets/Travel/dollar-circle.imageset/dollar-circle.png
  UMM/Assets.xcassets/Travel/pencil.imageset/Contents.json
  UMM/Assets.xcassets/Travel/pencil.imageset/pencil.png
  UMM/Assets.xcassets/Travel/xmark_gray.imageset/Contents.json
  UMM/Assets.xcassets/Travel/xmark_gray.imageset/xmark_gray.png
  UMM/Assets.xcassets/Travel/xmark_white.imageset/Contents.json
  UMM/Assets.xcassets/Travel/xmark_white.imageset/xmark_white.png
  UMM/View/Travel/NewView.swift
  UMM/View/Travel/PreviousTravelView.swift
  UMM/View/Travel/TravelDetailView.swift
  UMM/View/Travel/TravelListView.swift
  UMM/View/Travel/UpcomingTravelView.swift
  UMM/ViewModel/TravelListViewModel.swift
Labels: ⚡️ feat, :art: gui

#124 ⚡️[#122] TravelDetailView에 데이터를 추가합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/View/Travel/CompleteAddTravelView.swift
  UMM/View/Travel/PreviousTravelView.swift
  UMM/View/Travel/TravelDetailView.swift
  UMM/View/Travel/TravelListView.swift
  UMM/View/Travel/UpcomingTravelView.swift
  UMM/ViewModel/PreviousTravelViewModel.swift
  UMM/ViewModel/TravelDetailViewModel.swift
  UMM/ViewModel/UpcomingTravelViewModel.swift
Labels: ⚡️ feat, :art: gui

#125 ⚡ [#120] ExpenseView들을 연결합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/Handler/findCurrentTravel.swift
  UMM/View/Expense/AllExpenseDetailView.swift
  UMM/View/Expense/AllExpenseView.swift
  UMM/View/Expense/CustomDatePicker.swift
  UMM/View/Expense/ExpenseView.swift
  UMM/View/Expense/TodayExpenseDetailView.swift
  UMM/View/Expense/TodayExpenseView.swift
  UMM/View/Modal/TravelChoiceModal.swift
  UMM/View/Modal/TravelChoiceModalBinding.swift
  UMM/View/Other/DummyRecordView.swift
  UMM/ViewModel/DummyRecordViewModel.swift
  UMM/ViewModel/ExpenseViewModel.swift
Labels: ⚡️ feat

#133 ⚡️[#130] 국가 데이터를 추가하고 뷰와 연결합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/Assets.xcassets/Flag/AustraliaFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/AustraliaFlag.imageset/australia.png
  UMM/Assets.xcassets/Flag/CanadaFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/CanadaFlag.imageset/canada.png
  UMM/Assets.xcassets/Flag/CzechFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/CzechFlag.imageset/czech republic.png
  UMM/Assets.xcassets/Flag/DefaultFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/DefaultFlag.imageset/unknown.png
  UMM/Assets.xcassets/Flag/DenmarkFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/DenmarkFlag.imageset/denmark.png
  UMM/Assets.xcassets/Flag/GuamFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/GuamFlag.imageset/guam.png
  UMM/Assets.xcassets/Flag/HongkongFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/HongkongFlag.imageset/hong kong.png
  UMM/Assets.xcassets/Flag/HungaryFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/HungaryFlag.imageset/hungary.png
  UMM/Assets.xcassets/Flag/ItalyFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/ItalyFlag.imageset/italy.png
  UMM/Assets.xcassets/Flag/MacaoFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/MacaoFlag.imageset/macao.png
  UMM/Assets.xcassets/Flag/MongoliaFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/MongoliaFlag.imageset/mongolia.png
  UMM/Assets.xcassets/Flag/NetherlandFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/NetherlandFlag.imageset/netherlands.png
  UMM/Assets.xcassets/Flag/NewZealandFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/NewZealandFlag.imageset/new zealand.png
  UMM/Assets.xcassets/Flag/PhilippineFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/PhilippineFlag.imageset/philippines.png
  UMM/Assets.xcassets/Flag/SaipanFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/SaipanFlag.imageset/saipan.png
  UMM/Assets.xcassets/Flag/SingaporeFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/SingaporeFlag.imageset/singapore.png
  UMM/Assets.xcassets/Flag/SpainFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/SpainFlag.imageset/spain.png
  UMM/Assets.xcassets/Flag/SwissFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/SwissFlag.imageset/switzerland.png
  UMM/Assets.xcassets/Flag/ThailandFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/ThailandFlag.imageset/thailand.png
  UMM/Assets.xcassets/Flag/TurkeyFlag.imageset/Contents.json
  UMM/Assets.xcassets/Flag/TurkeyFlag.imageset/turkey.png
  UMM/Handler/parseCoutryDataFile.swift
  UMM/Model/CountryList.csv
  UMM/Model/Enumeration/Country.swift
  UMM/View/Travel/TravelListView.swift
  UMM/ViewModel/TravelListViewModel.swift
Labels: ⚡️ feat, :art: gui

#139 ⚡ [#137] 환율 API를 적용합니다.
  .DS_Store
  UMM.xcodeproj/project.pbxproj
  UMM.xcodeproj/xcshareddata/xcschemes/UMM.xcscheme
  UMM/Handler/ExchangeRateHandler.swift
  UMM/Model/Enumeration/Currency.swift
  UMM/View/Expense/AllExpenseDetailView.swift
  UMM/View/Expense/AllExpenseView.swift
  UMM/View/Expense/ExpenseView.swift
  UMM/View/Expense/TodayExpenseDetailView.swift
  UMM/View/Expense/TodayExpenseView.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/View/Travel/TravelListView.swift
  UMM/ViewModel/ManualRecordViewModel.swift
Labels: ⚡️ feat, :art: gui
