Repository DeveloperAcademy-POSTECH/MacC-Team11-UMM, pull requests merged in 2023-11, with the labels that each got.

#141 🎨[#132] ManualRecordView의 여행 선택 모달 구현
  UMM.xcodeproj/project.pbxproj
  UMM/View/Modal/CountryChoiceModal.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/ViewModel/ManualRecordViewModel.swift
Labels: :art: gui

#144 🎨[#142] ManualRecordView를 어느 정도 완성합니다.
  UMM/View/Modal/CountryChoiceModal.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/View/Record/RecordView.swift
  UMM/ViewModel/ManualRecordViewModel.swift
  UMM/ViewModel/RecordViewModel.swift
Labels: :art: gui

#147 ⚡️[#143] csv파일에서 불러온 Country 데이터를 구조화하고 싱글톤 패턴을 적용합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/Handler/parseCoutryDataFile.swift
  UMM/Model/CountryInfo.swift
  UMM/Model/CountryInfoModel.swift
  UMM/View/Travel/PreviousTravelView.swift
  UMM/View/Travel/TravelDetailView.swift
  UMM/View/Travel/TravelListView.swift
  UMM/View/Travel/UpcomingTravelView.swift
  UMM/ViewModel/PreviousTravelViewModel.swift
  UMM/ViewModel/UpcomingTravelViewModel.swift
Labels: ⚡️ feat, :art: gui

#148 ⚡️[#99] 키보드 바깥을 터치하면 키보드가 내려가는 기능을 추가합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/Extension/Gesture+Extension.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/View/Travel/AddMemberView.swift
Labels: ⚡️ feat

#150 🎨 ⚡[#146] RecordViewModel과 RecordView를 개선합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/View/Modal/AddTravelRequestModal.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/View/Record/RecordView.swift
  UMM/ViewModel/RecordViewModel.swift
Labels: ⚡️ feat, :art: gui

#153 ⚡ [#145] 미뤄왔던 리팩토링을 하고, 작은 기능들을 수정합니다.
  .DS_Store
  UMM.xcodeproj/project.pbxproj
  UMM/Extension/NSObject+Extension.swift
  UMM/Model/UMM.xcdatamodeld/UMM.xcdatamodel/contents
  UMM/View/Expense/AllExpenseDetailView.swift
  UMM/View/Expense/AllExpenseView.swift
  UMM/View/Expense/CustomDatePicker.swift
  UMM/View/Expense/ExpenseView.swift
  UMM/View/Expense/TodayExpenseView.swift
  UMM/View/Modal/TravelChoiceModalBinding.swift
  UMM/ViewModel/ExpenseViewModel.swift
Labels: ⚡️ feat, :art: gui

#154 ⚡️[#135] MainViewModel을 구현하고 선택된 여행을 관리합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/View/Expense/ExpenseView.swift
  UMM/View/MainView.swift
  UMM/View/Record/RecordView.swift
  UMM/View/Travel/CompleteAddTravelView.swift
  UMM/View/Travel/PreviousTravelView.swift
  UMM/View/Travel/TravelDetailView.swift
  UMM/View/Travel/TravelListView.swift
  UMM/View/Travel/UpcomingTravelView.swift
  UMM/ViewModel/MainViewModel.swift
  UMM/ViewModel/TravelDetailViewModel.swift
Labels: ⚡️ feat

#155 🎨[#151] 여행 선택 모달을 수정합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/Model/CountryList.csv
  UMM/View/Expense/ExpenseView.swift
  UMM/View/Expense/TodayExpenseView.swift
  UMM/View/Modal/AddTravelRequestModal.swift
  UMM/View/Modal/CountryChoiceModal.swift
  UMM/View/Modal/TravelChoiceInExpenseModal.swift
  UMM/View/Modal/TravelChoiceInRecordModal.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/ViewModel/MainViewModel.swift
  UMM/ViewModel/ManualRecordViewModel.swift
Labels: :art: gui

#162 ⚡[#159] DateGapHandler 구현
  .DS_Store
  UMM.xcodeproj/project.pbxproj
  UMM/Handler/DateGapHandler.swift
  UMM/View/Modal/TravelChoiceInExpenseModal.swift
  UMM/View/Modal/TravelChoiceInRecordModal.swift
  UMM/ViewModel/ManualRecordViewModel.swift
  UMM/ViewModel/Redrawer.swift
Labels: ⚡️ feat

#158 ⚡ [#145] -1 문제를 해결합니다. barGraph 문제를 해결합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/View/Expense/AllExpenseDetailView.swift
  UMM/View/Expense/AllExpenseView.swift
  UMM/View/Expense/ExpenseView.swift
  UMM/View/Expense/TodayExpenseDetailView.swift
  UMM/View/Expense/TodayExpenseView.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/ViewModel/ExpenseViewModel.swift
  UMM/ViewModel/ManualRecordViewModel.swift
Labels: ⚡️ feat, :art: gui

#164 ⚡[#161] MainViewModel의 여행 선택과 지출 기록 탭을 연결했습니다.
  UMM.xcodeproj/project.pbxproj
  UMM/View/MainView.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/View/Record/RecordView.swift
  UMM/ViewModel/MainViewModel.swift
  UMM/ViewModel/ManualRecordViewModel.swift
  UMM/ViewModel/RecordViewModel.swift
Labels: ⚡️ feat

#165 ⚡ [#152] RecordView에서 각 항목이 업데이트 되었을 때 햅틱을 구현했습니다.
  UMM/View/Record/RecordView.swift
  UMM/ViewModel/RecordViewModel.swift
Labels: ⚡️ feat

#166 🎨 [#163] TodayExpenseVIew와 AllExpenseView에 지출 기록이 없는 경우, 표시할 View 추가
  UMM/View/Expense/AllExpenseView.swift
  UMM/View/Expense/TodayExpenseView.swift
Labels: :art: gui

#170 ⚡ [#167] CurrencyInfo 관련 코드를 작성했습니다. 이후 Expense 관련 뷰에 적용했습니다.
  UMM.xcodeproj/project.pbxproj
  UMM/.DS_Store
  UMM/Model/CountryInfo.swift
  UMM/Model/CountryInfoModel.swift
  UMM/Model/CountryList.csv
  UMM/Model/CurrencyInfo.swift
  UMM/Model/CurrencyInfoModel.swift
  UMM/Model/CurrencyList.csv
  UMM/View/Expense/AllExpenseDetailView.swift
  UMM/View/Expense/AllExpenseView.swift
  UMM/View/Expense/ExpenseView.swift
  UMM/View/Expense/TodayExpenseDetailView.swift
  UMM/View/Expense/TodayExpenseView.swift
  UMM/ViewModel/RecordViewModel.swift
Labels: ⚡️ feat

#180 ⚡ [#171] Expense 관련 뷰에 MainViewModel을 적용했습니다.
  UMM/Model/.DS_Store
  UMM/View/Expense/AllExpenseDetailView.swift
  UMM/View/Expense/AllExpenseView.swift
  UMM/View/Expense/ExpenseView.swift
  UMM/View/Expense/TodayExpenseDetailView.swift
  UMM/View/Expense/TodayExpenseView.swift
  UMM/View/Modal/TravelChoiceInExpenseModal.swift
  UMM/View/Travel/TravelListView.swift
  UMM/ViewModel/ExpenseViewModel.swift
  UMM/ViewModel/MainViewModel.swift
Labels: ⚡️ feat

#181 ⚡️🎨[#156][#157] TravelListView의 자잘한 수정과 InterimRecordView를 구현합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/DesignSystem/ButtonTheme.swift
  UMM/View/Record/InterimOncomingView.swift
  UMM/View/Record/InterimPastView.swift
  UMM/View/Record/InterimProceedingView.swift
  UMM/View/Record/InterimRecordView.swift
  UMM/View/Travel/CompleteAddTravelView.swift
  UMM/View/Travel/PreviousTravelView.swift
  UMM/View/Travel/TravelListView.swift
  UMM/View/Travel/UpcomingTravelView.swift
  UMM/ViewModel/InterimRecordViewModel.swift
  UMM/ViewModel/TravelListViewModel.swift
Labels: ⚡️ feat, :art: gui

#183 ⚡ 🎨 [#173] Expense 관련 뷰에 CountryInfo를 적용합니다. 국기 이미지를 HIFI에 맞춰 수정합니다.
  UMM/View/Expense/AllExpenseView.swift
  UMM/View/Expense/TodayExpenseDetailView.swift
  UMM/View/Expense/TodayExpenseView.swift
  UMM/ViewModel/ExpenseViewModel.swift
Labels: ⚡️ feat, :art: gui

#182 🎨[#160] RecordView, ManualRecordView를 수정합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/Assets.xcassets/Record/recordBigMainPinkCheck.imageset/Contents.json
  UMM/Assets.xcassets/Record/recordBigMainPinkCheck.imageset/recordBigMainPinkCheck.png
  UMM/Assets.xcassets/Record/recordGrayPencil.imageset/Contents.json
  UMM/Assets.xcassets/Record/recordGrayPencil.imageset/manualRecordPencil.png
  UMM/View/.DS_Store
  UMM/View/Modal/CountryChoiceModal.swift
  UMM/View/Modal/DateChoiceModal.swift
  UMM/View/Record/CompleteRecordView.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/View/Record/RecordView.swift
  UMM/ViewModel/MainViewModel.swift
  UMM/ViewModel/ManualRecordViewModel.swift
  UMM/ViewModel/RecordViewModel.swift
Labels: :art: gui

#186 ⚡️[#157] InterimRecordView의 기능을 구현합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/View/Record/InterimOncomingView.swift
  UMM/View/Record/InterimProceedingView.swift
  UMM/View/Record/InterimRecordView.swift
  UMM/View/Travel/TravelListView.swift
  UMM/ViewModel/InterimRecordViewModel.swift
Labels: ⚡️ feat

#187 ⚡ [#172] Expense 관련 뷰에 DateGapHandler를 적용합니다.
  UMM/Handler/dateFormatter.swift
  UMM/View/Expense/AllExpenseDetailView.swift
  UMM/View/Expense/CustomDatePicker.swift
  UMM/View/Expense/TodayExpenseDetailView.swift
  UMM/View/Expense/TodayExpenseView.swift
  UMM/ViewModel/ExpenseViewModel.swift
Labels: ⚡️ feat

#189 🧹[#185] 지출 기록 탭에 CountryInfo, CurrencyInfo, DateGapHandler 적용
  UMM.xcodeproj/project.pbxproj
  UMM/Dummy/TempSave.swift
  UMM/Extension/Date+Extension.swift
  UMM/Handler/DateGapHandler.swift
  UMM/Model/CountryList.csv
  UMM/Model/CurrencyList.csv
  UMM/View/Modal/CountryChoiceModal.swift
  UMM/View/Modal/TravelChoiceInRecordModal.swift
  UMM/View/Record/CompleteRecordView.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/ViewModel/ManualRecordViewModel.swift
Labels: ⚡️ feat, :broom: chore

#195 ⚡[#190] 녹음 파일을 코어 데이터에 저장했습니다.
  .DS_Store
  UMM/.DS_Store
  UMM/Assets.xcassets/.DS_Store
  UMM/Assets.xcassets/Default Image/.DS_Store
  UMM/Model/UMM.xcdatamodeld/UMM.xcdatamodel/contents
  UMM/View/Record/CompleteRecordView.swift
  UMM/ViewModel/ManualRecordViewModel.swift
  UMM/ViewModel/RecordViewModel.swift
Labels: ⚡️ feat

#197 🎨[#196] ManualRecordView 소소한 수정을 합니다.
  UMM/View/Record/ManualRecordView.swift
  UMM/View/Record/RecordView.swift
  UMM/ViewModel/ManualRecordViewModel.swift
  UMM/ViewModel/RecordViewModel.swift
Labels: ⚡️ feat, :art: gui

#201 ⚡ [#179] SettingView 구현 완료
  UMM.xcodeproj/project.pbxproj
  UMM/Extension/Font+Extension.swift
  UMM/View/Other/SettingView.swift
Labels: ⚡️ feat, :art: gui

#207 🎨[#176][#192] TravelDetailView의 UI 수정 및 캘린더 UI 수정
  UMM.xcodeproj/project.pbxproj
  UMM/DesignSystem/ButtonTheme.swift
  UMM/View/Travel/AddTravelView.swift
  UMM/View/Travel/PreviousTravelView.swift
  UMM/View/Travel/TravelDetailView.swift
  UMM/View/Travel/TravelListView.swift
  UMM/View/Travel/UpcomingTravelView.swift
Labels: :art: gui

#214 🎨[#198][#203] 국가 선택 모달, 상세 위치 플레이스홀더, 탭뷰
  UMM.xcodeproj/project.pbxproj
  UMM/View/Modal/TravelChoiceInExpenseModal.swift
  UMM/View/Modal/TravelChoiceInRecordModal.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/ViewModel/MainViewModel.swift
Labels: :art: gui

#221 ⚡ 🎨 [#218] DetailView와 ManualRecordInExpenseView를 연결하고 기능을 구현했습니다.
  UMM/View/Expense/AllExpenseDetailView.swift
  UMM/View/Expense/TodayExpenseDetailView.swift
  UMM/View/Record/ManualRecordInExpenseView.swift
  UMM/ViewModel/ManualRecordInExpenseViewModel.swift
Labels: ⚡️ feat, :art: gui

#224 ⚡️🎨[#216][#222] Travel 관련 뷰들의 수정사항을 반영합니다.
  UMM/View/Record/InterimOncomingView.swift
  UMM/View/Record/InterimPastView.swift
  UMM/View/Record/InterimProceedingView.swift
  UMM/View/Record/InterimRecordView.swift
  UMM/View/Travel/AddMemberView.swift
  UMM/View/Travel/AddTravelView.swift
  UMM/View/Travel/CompleteAddTravelView.swift
  UMM/View/Travel/PreviousTravelView.swift
  UMM/View/Travel/TravelDetailView.swift
  UMM/View/Travel/TravelListView.swift
  UMM/View/Travel/UpcomingTravelView.swift
  UMM/ViewModel/CompleteAddTravelViewModel.swift
  UMM/ViewModel/InterimRecordViewModel.swift
  UMM/ViewModel/TravelListViewModel.swift
Labels: ⚡️ feat, :art: gui

#231 🎨[#223][#227][#229] UI 섬세한 수정
  UMM.xcodeproj/project.pbxproj
  UMM/View/Modal/AddTravelRequestModal.swift
  UMM/View/Modal/TravelChoiceInRecordModal.swift
  UMM/View/Record/ManualRecordInExpenseView.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/View/Record/RecordView.swift
  UMM/ViewModel/ManualRecordViewModel.swift
  UMM/ViewModel/RecordViewModel.swift
Labels: :art: gui

#234 🧹[#232] 국기 선택 알고리즘 수정 등
  UMM/View/Modal/TravelChoiceInExpenseModal.swift
  UMM/View/Modal/TravelChoiceInRecordModal.swift
  UMM/ViewModel/ManualRecordInExpenseViewModel.swift
  UMM/ViewModel/ManualRecordViewModel.swift
Labels: :broom: chore

#235 🐛 ⚡ 🎨 [#219][#230][#233] ManualRecordView의 저장하기 문제를 해결합니다. selectedTravel을 연동합니다. 각종 버그 해결합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/Extension/Date+Extension.swift
  UMM/View/Expense/AllExpenseDetailView.swift
  UMM/View/Expense/CustomDatePicker.swift
  UMM/View/Expense/ExpenseView.swift
  UMM/View/Expense/TodayExpenseDetailView.swift
  UMM/View/Expense/TodayExpenseView.swift
  UMM/View/Record/ManualRecordInExpenseView.swift
  UMM/ViewModel/ExpenseViewModel.swift
  UMM/ViewModel/MainViewModel.swift
  UMM/ViewModel/ManualRecordInExpenseViewModel.swift
Labels: :hammer: bug, ⚡️ feat, :art: gui

#239 🐛 ⚡ [#219][#238] customDatePicker의 화살표 이미지를 변경합니다. 버그를 해결합니다.
  UMM/Assets.xcassets/Expense/activatedLeft.imageset/Contents.json
  UMM/Assets.xcassets/Expense/activatedLeft.imageset/activatedLeft.png
  UMM/Assets.xcassets/Expense/activatedRight.imageset/Contents.json
  UMM/Assets.xcassets/Expense/activatedRight.imageset/activatedRight.png
  UMM/Assets.xcassets/Expense/inActivatedLeft.imageset/Contents.json
  UMM/Assets.xcassets/Expense/inActivatedLeft.imageset/inActivatedLeft.png
  UMM/Assets.xcassets/Expense/inActivatedRight.imageset/Contents.json
  UMM/Assets.xcassets/Expense/inActivatedRight.imageset/inActivatedRight.png
  UMM/View/Expense/AllExpenseView.swift
  UMM/View/Expense/CustomDatePicker.swift
  UMM/View/Expense/TodayExpenseDetailView.swift
  UMM/View/Expense/TodayExpenseView.swift
  UMM/View/MainView.swift
  UMM/View/Record/ManualRecordInExpenseView.swift
  UMM/ViewModel/ManualRecordInExpenseViewModel.swift
Labels: :hammer: bug, ⚡️ feat, :art: gui

#243 🐛 🎨 [#236][#237] 여행 endDate 문제 해결, 여행 생성 권유 모달 탭 전환 활성화
  UMM.xcodeproj/project.pbxproj
  UMM/Handler/DateGapHandler.swift
  UMM/View/Modal/AddTravelRequestModal.swift
  UMM/View/Travel/AddMemberView.swift
Labels: :hammer: bug, :art: gui

#244 🎨[#241] 모든 하단 버튼 위치의 수정합니다.
  UMM/DesignSystem/ButtonTheme.swift
  UMM/View/Modal/AddTravelRequestModal.swift
  UMM/View/Record/InterimRecordView.swift
  UMM/View/Record/ManualRecordInExpenseView.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/View/Travel/AddMemberView.swift
  UMM/View/Travel/AddTravelView.swift
  UMM/View/Travel/CompleteAddTravelView.swift
  UMM/View/Travel/TravelDetailView.swift
Labels: :art: gui

#252 :bug:[#249] AllDetail 빨간 글씨 수정
  UMM/View/Expense/AllExpenseDetailView.swift
Labels: :hammer: bug

#254 :bug:[#249] divider padding 조절
  UMM.xcodeproj/project.pbxproj
  UMM/View/Expense/AllExpenseDetailView.swift
  UMM/View/Expense/AllExpenseView.swift
  UMM/View/Expense/ExpenseView.swift
  UMM/View/Expense/TodayExpenseDetailView.swift
  UMM/View/Expense/TodayExpenseView.swift
Labels: :hammer: bug

#257 :bug:[#249] 임시 기록을 되살려냈다
  UMM/Dummy/TempSave.swift
  UMM/Handler/findCurrentTravel.swift
  UMM/View/Travel/AddMemberView.swift
Labels: :hammer: bug

#258 :bug:[#249] ManualRecordInExpenseView에서 날짜 피커 에러
  UMM/Extension/Date+Extension.swift
  UMM/ViewModel/ManualRecordInExpenseViewModel.swift
Labels: :hammer: bug

#260 :bug:[#259] 위치 정보 허용 창 안 떠서 앱이 멈춰보이는 문제 해결
  UMM/Handler/DateGapHandler.swift
  UMM/View/MainView.swift
Labels: :hammer: bug

#261 🔨[#259] 임시기록을 삭제해도 뷰가 업데이트되지 않는 오류를 해결합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/View/Travel/TravelListView.swift
Labels: :hammer: bug

#262 🐛[#259] 위치 정보 허용 창이 안 떠서 앱이 멈추는 오류 해결(2)
  UMM.xcodeproj/project.pbxproj
  UMM/Handler/DateGapHandler.swift
  UMM/View/MainView.swift
Labels: :hammer: bug

#263 🎨[#259] 스플래시 뷰 구현합니다.
  UMM.xcodeproj/project.pbxproj
  UMM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  UMM/DesignSystem/Splash.json
  UMM/UMMApp.swift
  UMM/View/Other/LottieView.swift
  UMM/View/Other/SplashView.swift
Labels: :art: gui

#274 🎨[#271] 여러 수정사항 반영
  .DS_Store
  UMM.xcodeproj/project.pbxproj
  UMM/DesignSystem/String+DesignSystem.swift
  UMM/Dummy/TempSave.swift
  UMM/View/Modal/TravelChoiceInRecordModal.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/ViewModel/ManualRecordInExpenseViewModel.swift
  UMM/ViewModel/ManualRecordViewModel.swift
  UMM/ViewModel/RecordViewModel.swift
Labels: :hammer: bug, ⚡️ feat, :art: gui

#275 🐛 [#269][#270] 환율 정보 문제를 해결합니다. 당근 에러를 해결합니다.
  .env
  .gitignore
  UMM.xcodeproj/project.pbxproj
  UMM/.DS_Store
  UMM/Env/Configuration.swift
  UMM/Handler/ExchangeRateHandler.swift
  UMM/Info.plist
  UMM/View/Config.xcconfig
  UMM/View/Expense/AllExpenseDetailView.swift
  UMM/View/MainView.swift
  UMM/View/Other/SettingView.swift
  UMM/View/Record/ManualRecordInExpenseView.swift
  UMM/View/Travel/TravelListView.swift
  UMM/ViewModel/ManualRecordInExpenseViewModel.swift
  UMM/ViewModel/ManualRecordViewModel.swift
Labels: :hammer: bug

#276 :bug:[#267] ManualRecordInExpenseView에서 participantArray가 정상 작동하도록 수정
  UMM/Handler/DateGapHandler.swift
  UMM/View/Record/ManualRecordInExpenseView.swift
  UMM/ViewModel/ManualRecordInExpenseViewModel.swift
  UMM/ViewModel/ManualRecordViewModel.swift
Labels: :hammer: bug

#279 ♻️[#278] 반복되어 사용되고 있는 뷰를 분리합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/View/Record/InterimOncomingView.swift
  UMM/View/Record/InterimPastView.swift
  UMM/View/Record/InterimProceedingView.swift
  UMM/View/Travel/PreviousTravelView.swift
  UMM/View/Travel/TravelButtonView.swift
  UMM/View/Travel/TravelItemView.swift
  UMM/View/Travel/UpcomingTravelView.swift
  UMM/ViewModel/TravelItemViewModel.swift
Labels: :recycle: refactor

#287 🐛🎨[#281][#283][#286] 녹음 버튼 크래시 해결, selectedTravel 등 문제 해결, 수정할 것들 수정
  UMM.xcodeproj/project.pbxproj
  UMM/.DS_Store
  UMM/Dummy/TempSave.swift
  UMM/Handler/findCurrentTravel.swift
  UMM/Handler/travelModalSortRule.swift
  UMM/Model/.DS_Store
  UMM/View/Modal/AddTravelRequestModal.swift
  UMM/View/Modal/CountryChoiceModal.swift
  UMM/View/Modal/DateChoiceModal.swift
  UMM/View/Modal/TravelChoiceInExpenseModal.swift
  UMM/View/Modal/TravelChoiceInRecordModal.swift
  UMM/View/Other/LottieView.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/View/Record/RecordView.swift
  UMM/View/Travel/AddMemberView.swift
  UMM/View/Travel/TravelDetailView.swift
  UMM/ViewModel/AddMemberViewModel.swift
  UMM/ViewModel/MainViewModel.swift
  UMM/ViewModel/ManualRecordInExpenseViewModel.swift
  UMM/ViewModel/ManualRecordViewModel.swift
  UMM/ViewModel/RecordViewModel.swift
Labels: ⚡️ feat, :art: gui

#289 🐛 ⚡ [#268][#272][#282]
  .DS_Store
  .gitignore
  UMM.xcodeproj/project.pbxproj
  UMM/.DS_Store
  UMM/Assets.xcassets/.DS_Store
  UMM/Assets.xcassets/Default Image/.DS_Store
  UMM/Assets.xcassets/Expense/trashCanGray.imageset/Contents.json
  UMM/Assets.xcassets/Expense/trashCanGray.imageset/용도=여행 프로필 페이지, 의미=trash, 선택 여부=gray.png
  UMM/Assets.xcassets/Record/recordButtonOn.imageset/Contents.json
  UMM/Env/.DS_Store
  UMM/Model/.DS_Store
  UMM/Model/Persistence.swift
  UMM/Model/UMM.xcdatamodeld/UMM.xcdatamodel/contents
  UMM/View/.DS_Store
  UMM/View/Expense/AllExpenseDetailView.swift
  UMM/View/Expense/AllExpenseView.swift
  UMM/View/Expense/ManualRecordInExpenseView.swift
  UMM/View/Expense/TodayExpenseDetailView.swift
  UMM/View/Expense/TodayExpenseView.swift
  UMM/View/Modal/TravelChoiceInExpenseModal.swift
  UMM/ViewModel/ExpenseViewModel.swift
  UMM/ViewModel/MainViewModel.swift
Labels: :hammer: bug, ⚡️ feat, :art: gui

#291 🎨 [#280][#288] CompleteAddTravelView와 AddMemberView의 UI를 수정합니다.
  UMM/Assets.xcassets/Travel/plus_white.imageset/Contents.json
  UMM/Assets.xcassets/Travel/plus_white.imageset/plus_white.png
  UMM/Assets.xcassets/Travel/xmark_circle.imageset/Contents.json
  UMM/Assets.xcassets/Travel/xmark_circle.imageset/xmark_circle.png
  UMM/DesignSystem/ButtonTheme.swift
  UMM/View/Travel/AddMemberView.swift
  UMM/View/Travel/AddTravelView.swift
  UMM/View/Travel/CompleteAddTravelView.swift
  UMM/View/Travel/TravelButtonView.swift
  UMM/View/Travel/TravelDetailView.swift
  UMM/View/Travel/TravelItemView.swift
  UMM/View/Travel/TravelListView.swift
  UMM/ViewModel/AddTravelViewModel.swift
  UMM/ViewModel/CompleteAddTravelViewModel.swift
Labels: :art: gui

#293 🐛 ♻️ [#290] ManualRecordInExpenseView와 ViewModel을 ManualRecord와 동기화 합니다. 고질적인 에러 몇 가지를 고쳤습니다.
  UMM/Assets.xcassets/Record/recordButtonOff.imageset/Contents.json
  UMM/Assets.xcassets/Record/recordButtonOff.imageset/Image.png
  UMM/Assets.xcassets/Record/recordButtonOff.imageset/nonRecording.png
  UMM/Assets.xcassets/Record/recordButtonOn.imageset/Contents.json
  UMM/Assets.xcassets/Record/recordButtonOn.imageset/buttonRecording.png
  UMM/Assets.xcassets/Record/recordButtonOn.imageset/녹음 여부4 1.png
  UMM/Handler/findCurrentTravel.swift
  UMM/View/Expense/CustomDatePicker.swift
  UMM/View/Expense/ExpenseView.swift
  UMM/View/Expense/ManualRecordInExpenseView.swift
  UMM/View/Modal/TravelChoiceInRecordModal.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/View/Record/RecordView.swift
  UMM/ViewModel/MainViewModel.swift
  UMM/ViewModel/ManualRecordInExpenseViewModel.swift
  UMM/ViewModel/ManualRecordViewModel.swift
Labels: :recycle: refactor, :hammer: bug

#296 🎨 [#290] AllDetailView의 gui를 수정했습니다.
  UMM/View/Expense/AllExpenseDetailView.swift
Labels: :art: gui

#297 🧹 [#294][#295] 위치 정보 문구 수정, 넘버 포매터 분리
  UMM.xcodeproj/project.pbxproj
  UMM/.DS_Store
  UMM/Extension/Double+Extension.swift
  UMM/Handler/NumberFormatter.swift
  UMM/Handler/travelModalSortRule.swift
  UMM/Info.plist
  UMM/View/Expense/ManualRecordInExpenseView.swift
  UMM/View/Modal/TravelChoiceInRecordModal.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/View/Record/RecordView.swift
  UMM/ViewModel/ManualRecordViewModel.swift
Labels: :broom: chore

#298 :bug:[#290] 임시 기록일 때는 항상 텅 뷰로
  UMM.xcodeproj/project.pbxproj
  UMM/View/Expense/AllExpenseView.swift
  UMM/View/Expense/TodayExpenseView.swift
Labels: :hammer: bug

#300 🧹[#299] 버튼 색 수정
  UMM.xcodeproj/project.pbxproj
  UMM/View/Modal/AddTravelRequestModal.swift
Labels: :art: gui

#306 :bug:[#304] QA에 따른 긴급 수정 사항을 적용합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/Assets.xcassets/Expense/trashCanGray.imageset/Contents.json
  UMM/Assets.xcassets/Expense/trashCanGray.imageset/trashCanGray.png
  UMM/View/Expense/ManualRecordInExpenseView.swift
  UMM/View/Other/SettingView.swift
Labels: :hammer: bug

#310 🎨⚡️[#307][#308] (Travel 관련) 버전 1.1.1이후 수정사항들을 반영합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/View/Travel/AddMemberView.swift
  UMM/View/Travel/CompleteAddTravelView.swift
  UMM/View/Travel/TravelButtonView.swift
  UMM/View/Travel/TravelDetailView.swift
  UMM/ViewModel/AddMemberViewModel.swift
  UMM/ViewModel/InterimRecordViewModel.swift
  UMM/ViewModel/PreviousTravelViewModel.swift
  UMM/ViewModel/TravelListViewModel.swift
  UMM/ViewModel/UpcomingTravelViewModel.swift
Labels: ⚡️ feat, :art: gui

#313 🔨[#311] 최초 임시기록 시 UI가 깨지는 오류를 해결합니다.
  UMM/View/Travel/TravelDetailView.swift
  UMM/View/Travel/TravelListView.swift
  UMM/View/Travel/UpcomingTravelView.swift
Labels: :hammer: bug

#319 🎨 [#314][#317][#318] 고정 폰트 추가, Currency 이뉴머레이션 사용하는 코드 수정
  UMM.xcodeproj/project.pbxproj
  UMM/Extension/Font+Extension.swift
  UMM/Model/Enumeration/Country.swift
  UMM/Model/Enumeration/Currency.swift
  UMM/View/Expense/AllExpenseDetailView.swift
  UMM/View/Expense/AllExpenseView.swift
  UMM/View/Expense/TodayExpenseDetailView.swift
  UMM/View/Record/ManualRecordView.swift
  UMM/View/Record/RecordView.swift
Labels: :art: gui

#326 🎨[#325] record 수정할 것들 수정
  UMM.xcodeproj/project.pbxproj
  UMM/Assets.xcassets/AccentColor.colorset/Contents.json
  UMM/Assets.xcassets/Modal/modalCategoryFood.imageset/Contents.json
  UMM/Assets.xcassets/Modal/modalCategoryFood.imageset/manualRecordCategoryFood.png
  UMM/Assets.xcassets/Modal/modalCategoryFun.imageset/Contents.json
  UMM/Assets.xcassets/Modal/modalCategoryFun.imageset/manualRecordCategoryFun.png
  UMM/Assets.xcassets/Modal/modalCategoryGift.imageset/Contents.json
  UMM/Assets.xcassets/Modal/modalCategoryGift.imageset/modalCategoryGift.png
  UMM/Assets.xcassets/Modal/modalCategoryPlane.imageset/Contents.json
  UMM/Assets.xcassets/Modal/modalCategoryPlane.imageset/manualRecordCategoryPlane.png
  UMM/Assets.xcassets/Modal/modalCategoryRoom.imageset/Contents.json
  UMM/Assets.xcassets/Modal/modalCategoryRoom.imageset/manualRecordCategoryRoom.png
  UMM/Assets.xcassets/Modal/modalCategoryShopping.imageset/Contents.json
  UMM/Assets.xcassets/Modal/modalCategoryShopping.imageset/manualRecordCategoryShopping.png
  UMM/Assets.xcassets/Modal/modalCategoryTransportation.imageset/Contents.json
  UMM/Assets.xcassets/Modal/modalCategoryTransportation.imageset/manualRecordCategoryTransportation.png
  UMM/Assets.xcassets/Modal/modalCategoryUnknown.imageset/Contents.json
  UMM/Assets.xcassets/Modal/modalCategoryUnknown.imageset/manualRecordCategoryUnknown.png
  UMM/Assets.xcassets/Primary/graphGreen.colorset/Contents.json
  UMM/Assets.xcassets/Record/manualRecordCategoryFood.imageset/Contents.json
  UMM/Assets.xcassets/Record/manualRecordCategoryFood.imageset/modalRecordCategoryFood.png
  UMM/Assets.xcassets/Record/manualRecordCategoryFun.imageset/Contents.json
  UMM/Assets.xcassets/Record/manualRecordCategoryFun.imageset/modalRecordCategoryTour.png
  UMM/Assets.xcassets/Record/manualRecordCategoryGift.imageset/Contents.json
  UMM/Assets.xcassets/Record/manualRecordCategoryGift.imageset/manualRecordCategoryGift.png
  UMM/Assets.xcassets/Record/manualRecordCategoryPlane.imageset/Contents.json
  UMM/Assets.xcassets/Record/manualRecordCategoryPlane.imageset/modalRecordCategoryPlane.png
  UMM/Assets.xcassets/Record/manualRecordCategoryRoom.imageset/Contents.json
  UMM/Assets.xcassets/Record/manualRecordCategoryRoom.imageset/modalRecordCategoryRoom.png
  UMM/Assets.xcassets/Record/manualRecordCategoryShopping.imageset/Contents.json
  UMM/Assets.xcassets/Record/manualRecordCategoryShopping.imageset/modalRecordCategoryShopping.png
  UMM/Assets.xcassets/Record/manualRecordCategoryTransportation.imageset/Contents.json
  UMM/Assets.xcassets/Record/manualRecordCategoryTransportation.imageset/modalRecordCategoryTransportation.png
  UMM/Assets.xcassets/Record/manualRecordCategoryUnknown.imageset/Contents.json
  UMM/Assets.xcassets/Record/manualRecordCategoryUnknown.imageset/modalRecordCategoryUnknown.png
  UMM/Handler/DateGapHandler.swift
  UMM/Model/Enumeration/ExpenseInfoCategory.swift
  UMM/View/Modal/CategoryChoiceModal.swift
  UMM/View/Other/SettingView.swift
  UMM/ViewModel/ManualRecordViewModel.swift
  UMM/ViewModel/RecordViewModel.swift
Labels: :art: gui

#331 🎨 [#327] 지출 기록 탭 SE 기종 대응, AI 모델 개선
  UMM.xcodeproj/project.pbxproj
  UMM/Model/InfoClassifier.mlmodel
  UMM/View/Record/RecordView.swift
Labels: ⚡️ feat, :art: gui

#336 🎨[#335] TravelListView의 화면을 SE 화면비율을 고려합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/Utils/Constants.swift
  UMM/View/Record/InterimOncomingView.swift
  UMM/View/Record/InterimPastView.swift
  UMM/View/Record/InterimProceedingView.swift
  UMM/View/Travel/PreviousTravelView.swift
  UMM/View/Travel/TravelButtonView.swift
  UMM/View/Travel/TravelItemView.swift
  UMM/View/Travel/UpcomingTravelView.swift
Labels: :art: gui

#337 🎨⚡[#334] 모든 커스텀 폰트를 fixedSize로 변경, 머신 러닝 모델 변경
  UMM.xcodeproj/project.pbxproj
  UMM/Extension/Font+Extension.swift
  UMM/Model/InfoClassifier.mlmodel
Labels: ⚡️ feat, :art: gui

#341 🎨 [#340] 탭바 위에 줄 긋기 구현
  UMM/View/MainView.swift
Labels: :art: gui

#347 :broom:[#345] .csv 관련 info.plist를 수정합니다.
  UMM.xcodeproj/project.pbxproj
  UMM/Info.plist
  UMM/View/Expense/CSVArchive.swift
Labels: :broom: chore
